name = "IndexedDFs"
uuid = "30d8e1a9-d5cd-4a57-ad5f-8276e63f4ed5"
authors = ["Patrick Staudt <patrickstaudt1@gmail.com>"]
version = "0.1.1-b0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"
DataFrames = "1"
